package rules
 
import co.com.suramericana.model.Product

rule "Offer for Shirt"
	when 
		productObject: Product(type=="shirt")
	then
		double precio = 32000;
		productObject.setDiscount(0.18);
		productObject.setPrice(precio - (precio * productObject.getDiscount()));
	end
rule "Offer for Pants"
	when 
		productObject: Product(type=="pants")
	then
		double precio = 5558054;
		productObject.setDiscount(0.65);
		productObject.setPrice(precio - (precio * productObject.getDiscount()));
	end