package accion
 
import co.com.suramericana.model.Product

rule "Offer for Ball"
	when 
		productObject: Product(type=="ball")
	then
		double precio = 54000;
		productObject.setDiscount(0.17);
		productObject.setPrice(precio - (precio * productObject.getDiscount()));
	end
rule "Offer for Racket"
	when 
		productObject: Product(type=="racket")
	then
		double precio = 80000;
		productObject.setDiscount(0.18);
		productObject.setPrice(precio - (precio * productObject.getDiscount()));
	end